title: Trung Dan Phan
description: |
  Hi there! ğŸ‘‹<br>
  I'm an aspiring data scientist passionate about creating innovative solutions.<br>
  During my free time, I love creating and sharing music. ğŸ¶<br><br>
  **Connect with me**:<br>
  - âœ‰ï¸ [trung-dan.phan@hec.edu](mailto:trung-dan.phan@hec.edu)<br>
  - ğŸŒ [LinkedIn](https://www.linkedin.com/in/trung-dan-phan/)<br>
  - ğŸµ [SoundCloud](https://soundcloud.com/adaname)

logo: /docs/headshot.png
# show_downloads: true
theme: jekyll-theme-minimal
