title: Trung Dan Phan
description: "| Hi there! ğŸ‘‹
  I'm an aspiring data scientist passionate about creating innovative solutions.
  During my free time, I love creating and sharing music. ğŸ¶  
  **Connect with me**:
  - âœ‰ï¸ [trung-dan.phan@hec.edu](trung-dan.phan@hec.edu)
  - ğŸŒ [LinkedIn](https://www.linkedin.com/in/trung-dan-phan/)
  - ğŸµ [SoundCloud](https://soundcloud.com/adaname)
  "
logo: /docs/headshot.png
# show_downloads: true
theme: jekyll-theme-minimal
