title: Trung Dan Phan
description: |
  Hi there! ğŸ‘‹<br>
  I'm an aspiring data scientist passionate about creating innovative solutions.<br>
  During my free time, I love recording and sharing music. ğŸ¶<br><br>
  <strong>Connect with me:</strong><br>
  - âœ‰ï¸ <a href="mailto:trung-dan.phan@hec.edu" target="_blank">Email</a><br>
  - ğŸŒ <a href="https://www.linkedin.com/in/trung-dan-phan/" target="_blank">LinkedIn</a><br>
  - ğŸµ <a href="https://soundcloud.com/adaname" target="_blank">SoundCloud</a>
logo: /docs/headshot.png
# show_downloads: true
theme: jekyll-theme-minimal
