title: Trung Dan Phan
description: "Hi there! ğŸ‘‹
  \nI'm an aspiring data scientist passionate about creating innovative solutions.
  During my free time, I love creating and sharing music. ğŸ¶  
  \n**Connect with me**:
  \n- âœ‰ï¸ [trung-dan.phan@hec.edu](trung-dan.phan@hec.edu)
  \n- ğŸŒ [LinkedIn](https://www.linkedin.com/in/trung-dan-phan/)
  \n- ğŸµ [SoundCloud](https://soundcloud.com/adaname)
  "
logo: /docs/headshot.png
# show_downloads: true
theme: jekyll-theme-minimal
